/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ReportsLiveRouteImport } from './routes/reports/live'
import { Route as ReportsSessionIdRouteImport } from './routes/reports/$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsLiveRoute = ReportsLiveRouteImport.update({
  id: '/reports/live',
  path: '/reports/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSessionIdRoute = ReportsSessionIdRouteImport.update({
  id: '/reports/$sessionId',
  path: '/reports/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reports/$sessionId': typeof ReportsSessionIdRoute
  '/reports/live': typeof ReportsLiveRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reports/$sessionId': typeof ReportsSessionIdRoute
  '/reports/live': typeof ReportsLiveRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reports/$sessionId': typeof ReportsSessionIdRoute
  '/reports/live': typeof ReportsLiveRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reports/$sessionId'
    | '/reports/live'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/reports/$sessionId' | '/reports/live' | '/reports'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/reports/$sessionId'
    | '/reports/live'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ReportsSessionIdRoute: typeof ReportsSessionIdRoute
  ReportsLiveRoute: typeof ReportsLiveRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/live': {
      id: '/reports/live'
      path: '/reports/live'
      fullPath: '/reports/live'
      preLoaderRoute: typeof ReportsLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$sessionId': {
      id: '/reports/$sessionId'
      path: '/reports/$sessionId'
      fullPath: '/reports/$sessionId'
      preLoaderRoute: typeof ReportsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ReportsSessionIdRoute: ReportsSessionIdRoute,
  ReportsLiveRoute: ReportsLiveRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
